### ISSUE TITLE
ros2_demo not found

### ISSUE THREAD

**Issue by yusam123** [emqx/bootcamp#14]
I came across from the blog https://www.emqx.com/en/blog/mqtt-and-micro-ros

Thanks so much for this interesting project. I am trying to follow the instructions on the blog, but I can not find the "mqtt-and-ros" directory in this repository.

**Comment by zmstone** [comment]
Just merged PR which added it, could you check again.
https://github.com/emqx/bootcamp/tree/main/mqtt-demo/mqtt-and-microros

Disclaimer: I am completely new to this topic.

**Comment by yusam123** [comment]
Found! Thank you!
